from inline_snapshot import external, register_format_alias, snapshot

register_format_alias(".html", ".txt")

workflow_show = snapshot(
    {
        (("show_description", True), ("description", ""), ("show_source", True)): external(
            "hash:456cabfd88f0*.html"
        ),
        (
            ("show_description", True),
            ("description", "Custom heading"),
            ("show_source", True),
        ): external("hash:e4226d16352e*.html"),
        (("show_description", False), ("description", ""), ("show_source", False)): external(
            "hash:78feb92e4171*.html"
        ),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:f90542b4e3cb*.html"),
        (
            ("show_heading", True),
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:ac47b3b93370*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 3),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:1322d6390dbc*.html"),
        (
            ("show_signature", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
            ("signature_show_secrets", True),
            ("signature_show_permissions", True),
        ): external("hash:d2e25cb02f37*.html"),
        (
            ("show_signature", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
            ("signature_show_secrets", True),
            ("signature_show_permissions", False),
        ): external("hash:cdf58c1c57a8*.html"),
        (
            ("show_signature", True),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
            ("signature_show_secrets", False),
            ("signature_show_permissions", True),
        ): external("hash:8df27f9a94e1*.html"),
        (
            ("show_signature", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
            ("signature_show_secrets", False),
            ("signature_show_permissions", False),
        ): external("hash:2500c66e1646*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:cb58c01daaeb*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:8648f88cc212*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:50af14995537*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:c00418e99257*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:3f50016a2686*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:757b79d7975f*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:4b4fbfc27652*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:92bd52ad97f5*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:93bf082d40ca*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:7d6a6f97b26c*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:af4931df88d0*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:22929d6c2b70*.html"),
    }
)

action_show = snapshot(
    {
        (("show_description", True), ("description", ""), ("show_source", True)): external(
            "hash:c2d04585861e*.html"
        ),
        (
            ("show_description", True),
            ("description", "Custom heading"),
            ("show_source", True),
        ): external("hash:cc9ff86b6acc*.html"),
        (("show_description", False), ("description", ""), ("show_source", False)): external(
            "hash:5a2f11e94bc0*.html"
        ),
        (
            ("show_signature", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
        ): external("hash:37c546e4acea*.html"),
        (
            ("show_signature", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
        ): external("hash:1bb484ae2f4d*.html"),
        (
            ("show_signature", True),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
        ): external("hash:0c67cdd8572d*.html"),
        (
            ("show_signature", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
        ): external("hash:98e4b6474a6f*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:25090fe68096*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:ce8c324c6d38*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:c2181f9e06dd*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:9536cc7cfc76*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:314a0e4ec397*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:b972a05ffc56*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:5a31bebe73cd*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:73064e20f309*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:28df0ab9fe56*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:99ee5da4993d*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:0cb5db6b0e9e*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:cdad9a8909ec*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:2eb63f18b2d0*.html"),
        (
            ("show_heading", True),
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:856a4ff20ee1*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", True),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:0a37a4286738*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 2),
            ("show_branding", True),
            ("branding_icon", "green"),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:3cb099624d88*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 3),
            ("show_branding", True),
            ("branding_icon", ""),
            ("branding_icon_color", "github"),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:c50b7f91aaff*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:c8c895c400f0*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:36d559797138*.html"),
    }
)
