from inline_snapshot import external, register_format_alias, snapshot

register_format_alias(".html", ".txt")


action_show = snapshot(
    {
        (
            "workflow",
            ("description", ""),
            ("show_description", True),
            ("show_source", True),
        ): external("hash:c7a144a3a5f1*.html"),
        (
            "workflow",
            ("description", "Custom heading"),
            ("show_description", True),
            ("show_source", True),
        ): external("hash:fc91d4ffface*.html"),
        (
            "workflow",
            ("description", ""),
            ("show_description", False),
            ("show_source", False),
        ): external("hash:fa8aeb1ce1b5*.html"),
        (
            "action",
            ("description", ""),
            ("show_description", True),
            ("show_source", True),
        ): external("hash:56a75289a57c*.html"),
        (
            "action",
            ("description", "Custom heading"),
            ("show_description", True),
            ("show_source", True),
        ): external("hash:ef78405111c9*.html"),
        (
            "action",
            ("description", ""),
            ("show_description", False),
            ("show_source", False),
        ): external("hash:5a2f11e94bc0*.html"),
        (
            "action",
            ("heading", ""),
            ("heading_level", 1),
            ("show_action_branding", False),
            ("show_action_branding_toc", False),
            ("show_heading", True),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:a9563e04d3bf*.html"),
        (
            "action",
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_action_branding", False),
            ("show_action_branding_toc", False),
            ("show_heading", True),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:8e367d1a8814*.html"),
        (
            "action",
            ("heading", ""),
            ("heading_level", 3),
            ("show_action_branding", True),
            ("show_action_branding_toc", True),
            ("show_heading", True),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:183590c571f5*.html"),
        (
            "action",
            ("heading", ""),
            ("heading_level", 1),
            ("show_action_branding", False),
            ("show_action_branding_toc", False),
            ("show_heading", False),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:00a90d893b8f*.html"),
        (
            "action",
            ("heading", ""),
            ("heading_level", 1),
            ("show_action_branding", False),
            ("show_action_branding_toc", False),
            ("show_heading", False),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:2cc6a5f50854*.html"),
        (
            "action",
            ("show_signature", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
        ): external("hash:37c546e4acea*.html"),
        (
            "action",
            ("show_signature", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
        ): external("hash:1bb484ae2f4d*.html"),
        (
            "action",
            ("show_signature", True),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
        ): external("hash:0c67cdd8572d*.html"),
        (
            "action",
            ("show_signature", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
        ): external("hash:98e4b6474a6f*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
        ): external("hash:e5989c758e3f*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
        ): external("hash:db184709685c*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
        ): external("hash:c2181f9e06dd*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
        ): external("hash:16a033cc9545*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
        ): external("hash:ccc43bb2c783*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
        ): external("hash:b972a05ffc56*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
        ): external("hash:b9bab3882ec1*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
        ): external("hash:d49b6f6b7139*.html"),
        (
            "action",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
        ): external("hash:28df0ab9fe56*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
        ): external("hash:b26146f6d737*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
        ): external("hash:9947fcdf68ab*.html"),
        (
            "action",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
        ): external("hash:cdad9a8909ec*.html"),
        (
            "workflow",
            ("heading", ""),
            ("heading_level", 1),
            ("show_heading", True),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:3b3da3dfa473*.html"),
        (
            "workflow",
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_heading", True),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:fed8b322ecca*.html"),
        (
            "workflow",
            ("heading", ""),
            ("heading_level", 3),
            ("show_heading", False),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:79363d5973a8*.html"),
        (
            "workflow",
            ("show_signature", True),
            ("signature_show_permissions", True),
            ("signature_show_secrets", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
        ): external("hash:3dceddc7c760*.html"),
        (
            "workflow",
            ("show_signature", True),
            ("signature_show_permissions", False),
            ("signature_show_secrets", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
        ): external("hash:39dc48bae2ed*.html"),
        (
            "workflow",
            ("show_signature", True),
            ("signature_show_permissions", True),
            ("signature_show_secrets", False),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
        ): external("hash:795a4b144630*.html"),
        (
            "workflow",
            ("show_signature", False),
            ("signature_show_permissions", False),
            ("signature_show_secrets", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
        ): external("hash:b7b94f302ddd*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
        ): external("hash:b2b5f54cb8bb*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:1cb275643524*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:cf268df3bbeb*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
        ): external("hash:32495b73807a*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:15bdc3f02f90*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:f2c3ccf68a8e*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
        ): external("hash:34eb5510de26*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:8539107d731f*.html"),
        (
            "workflow",
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:95296d813698*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
        ): external("hash:3e2bb700daed*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:db648413c43f*.html"),
        (
            "workflow",
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
        ): external("hash:4d5e64a56403*.html"),
    }
)
