from inline_snapshot import external, register_format_alias, snapshot

register_format_alias(".html", ".txt")

workflow_show = snapshot(
    {
        (
            ("show_signature", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
            ("signature_show_secrets", True),
            ("signature_show_permissions", True),
        ): external("hash:d2e25cb02f37*.html"),
        (("show_description", True), ("description", ""), ("show_source", True)): external(
            "hash:78f74a133e98*.html"
        ),
        (
            ("show_description", True),
            ("description", "Custom heading"),
            ("show_source", True),
        ): external("hash:98ed5c777c16*.html"),
        (("show_description", False), ("description", ""), ("show_source", False)): external(
            "hash:78feb92e4171*.html"
        ),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:f90542b4e3cb*.html"),
        (
            ("show_heading", True),
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:ac47b3b93370*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 3),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:1322d6390dbc*.html"),
        (
            ("show_signature", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
            ("signature_show_secrets", True),
            ("signature_show_permissions", False),
        ): external("hash:580dbb72a430*.html"),
        (
            ("show_signature", True),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
            ("signature_show_secrets", False),
            ("signature_show_permissions", True),
        ): external("hash:8df27f9a94e1*.html"),
        (
            ("show_signature", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
            ("signature_show_secrets", False),
            ("signature_show_permissions", False),
        ): external("hash:2500c66e1646*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:459e6df9404a*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:5a75c7bf0d0c*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:50af14995537*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:de1ce14a6155*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:c3d75cc82062*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:757b79d7975f*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:df4a79ccbc4e*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:d0d656ae3243*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:93bf082d40ca*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("show_secrets", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:f64c666c9ace*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:bbea0ecf08ae*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("show_secrets", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:22929d6c2b70*.html"),
    }
)

action_show = snapshot(
    {
        (("show_description", True), ("description", ""), ("show_source", True)): external(
            "hash:424cfa3fc1ae*.html"
        ),
        (
            ("show_description", True),
            ("description", "Custom heading"),
            ("show_source", True),
        ): external("hash:e4dcd796393b*.html"),
        (("show_description", False), ("description", ""), ("show_source", False)): external(
            "hash:5a2f11e94bc0*.html"
        ),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:0ceef1ac5031*.html"),
        (
            ("show_heading", True),
            ("heading", "Custom heading"),
            ("heading_level", 2),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", "Custom toc label"),
        ): external("hash:856a4ff20ee1*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", True),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:f95a81272438*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 2),
            ("show_branding", True),
            ("branding_icon", "green"),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:ec24ffcd90ef*.html"),
        (
            ("show_heading", True),
            ("heading", ""),
            ("heading_level", 3),
            ("show_branding", True),
            ("branding_icon", ""),
            ("branding_icon_color", "github"),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:28c7a6367a85*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", True),
            ("toc_label", ""),
        ): external("hash:c8c895c400f0*.html"),
        (
            ("show_heading", False),
            ("heading", ""),
            ("heading_level", 1),
            ("show_branding", False),
            ("branding_icon", ""),
            ("branding_icon_color", ""),
            ("show_toc_entry", False),
            ("toc_label", ""),
        ): external("hash:36d559797138*.html"),
        (
            ("show_signature", True),
            ("signature_version", "major"),
            ("signature_version_string", ""),
        ): external("hash:7091e40de6c7*.html"),
        (
            ("show_signature", True),
            ("signature_version", "semver"),
            ("signature_version_string", ""),
        ): external("hash:3d781cfae8ca*.html"),
        (
            ("show_signature", True),
            ("signature_version", "string"),
            ("signature_version_string", "latest"),
        ): external("hash:52da38d871e7*.html"),
        (
            ("show_signature", False),
            ("signature_version", "string"),
            ("signature_version_string", ""),
        ): external("hash:98e4b6474a6f*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:2d4f26c824aa*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:eeb3447bb48f*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "table"),
        ): external("hash:c2181f9e06dd*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:db3f3a39bba9*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:abf7bc96856b*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "table"),
        ): external("hash:b972a05ffc56*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:c645710e700a*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:06c007fcee4b*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "alphabetical"),
            ("parameters_section_style", "list"),
        ): external("hash:28df0ab9fe56*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", False),
            ("show_outputs", True),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:8f5c64c230a7*.html"),
        (
            ("show_inputs", True),
            ("show_inputs_only_required", True),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:855107f715cf*.html"),
        (
            ("show_inputs", False),
            ("show_inputs_only_required", False),
            ("show_outputs", False),
            ("parameters_order", "source"),
            ("parameters_section_style", "list"),
        ): external("hash:cdad9a8909ec*.html"),
    }
)
